app: Base
server: TarsprotocolProxy
template: tars.cpp
profile: ""
servants:
  - name: TarsProxyObj
    port: 20000
    isTars: false
    isTcp: true
    thread: 5
    capacity: 100000
    connection: 100000
    timeout: 60000
replicas: 3
hostNetwork: false
hostIPC: false
hostPorts: []
repo:
  id:
  image: tarscloud/base.tarsprotocolproxy
  secret: tars-image-secret
config:
  - name: TarsprotocolProxy.conf
    content: |
      <conf>
        #tarsping_interval=0 表示不打开跨IDC用于心跳的tars_ping请求，其他为心跳间隔，单位 秒
        tarsping_interval=10

        <proxy>
            # 表示访问如下服务obj，不直接在集群的主控下面找，而是直接根据以下配置做指定转发
            Test.SumClientServer.SumClientObj1=Test.SumClientServer.SumClientObj@tcp -h 172.16.8.147 -t 60000 -p 10032
            Test.TestServer.TestObj=Test.TestServer.TestObj@-h 192.168.242.176 -p 8888 -t 60000 

        </proxy>

        <proxy_conn>
            # 通过发 tars_ping 请求保持长连接，根据业务需求去配置，主要用在外网转发时保持连接稳定
            Test.GetSum22Server.GetSumObj = Base.TarsprotocolProxy.TarsProxyObj@tcp -h 172.16.8.115 -t 60000 -p 8888
        </proxy_conn>

        <auth>
            # 是否打开ip授权，on 打开， off 关闭（关闭的时候，任何ip可以访问集群内的任何服务，一般只有内网转发才会这么配置）
            on_off=off
            
            # 按业务去配置，方便管理，这里业务名没有实际含义，只要不重复即可
            <test_buss_1>
                # obj = white ip
                Test.GetSumServer.GetSumObj=124.74.236.120|124.74.236.122	
            </test_buss_1>

            <news>
                News.HelloServer.HelloObj=124.74.236.11|124.74.236.12
            </news>

            # 全局添加ip白名单 或者 黑名单
            ip_white_list=1.1.1.1|2.2.2.2
            ip_black_list=3.3.3.3

        </auth>
      </conf>

